// Generated by generate-registry.sh — do not edit by hand.

import type {Project} from './types';
import {project as _smoke} from './_smoke';
import {project as named_it_then_what_cta_free} from './named-it-then-what-cta-free';
import {project as named_it_then_what_hook_correct} from './named-it-then-what-hook-correct';
import {project as named_it_then_what_hook_search} from './named-it-then-what-hook-search';
import {project as named_it_then_what_hook_spots} from './named-it-then-what-hook-spots';
import {project as named_it_then_what} from './named-it-then-what';

export const projects: Project[] = [
  _smoke,
  named_it_then_what_cta_free,
  named_it_then_what_hook_correct,
  named_it_then_what_hook_search,
  named_it_then_what_hook_spots,
  named_it_then_what,
];
