#!/usr/bin/env bash
# Regenerate ad-studio/src/projects/registry.ts from campaign folders.
set -e
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

HOME_DIR=$(agent_skills_resolve_home "$SCRIPT_DIR") || {
  echo "error: could not locate agent-skills repo" >&2
  exit 1
}
PROJECTS="$HOME_DIR/ad-studio/src/projects"
OUT="$PROJECTS/registry.ts"

{
  echo '// Generated by generate-registry.sh — do not edit by hand.'
  echo
  echo "import type {Project} from './types';"
  for dir in "$PROJECTS"/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    [ "$name" = "types.ts" ] && continue
    [ -f "$dir/index.ts" ] || [ -f "$dir/index.tsx" ] || continue
    ident=$(echo "$name" | sed -E 's/[^A-Za-z0-9]/_/g; s/^([0-9])/p_\1/')
    echo "import {project as $ident} from './$name';"
  done
  echo
  echo 'export const projects: Project[] = ['
  for dir in "$PROJECTS"/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    [ -f "$dir/index.ts" ] || [ -f "$dir/index.tsx" ] || continue
    ident=$(echo "$name" | sed -E 's/[^A-Za-z0-9]/_/g; s/^([0-9])/p_\1/')
    echo "  $ident,"
  done
  echo '];'
} > "$OUT"

echo "wrote $OUT"
